### ISSUE TITLE
cmd args are not appropriate

### ISSUE THREAD

**Issue by aneeshkp** [redhat-nfvpe/helm2go-operator-sdk#10]
**Describe the bug**
This tool creates a new operator from existing helm charts

**To Reproduce**
go run main.go 

**Expected behavior**
should show helm screen th, the command should be
go run main.go my-new-operators --api-version etc
help should show
usage hel2go-operator-sdk <new operator name> [flags]

Flags 
--api-version required
--helm-chart ( decide what is required and add proper validations)

This should be 
  --helm-chart string           Initialize go operators  with existing helm chart (<URL>, <repo>/<name>, or local path)

**Screenshots**

**Additional context**

**Comment by sjakati98** [comment]
Duplicate of #12

**Comment by aneeshkp** [comment]
Tested
