### ISSUE TITLE
 undefined: os.UserHomeDir

### ISSUE THREAD

**Issue by aneeshkp** [redhat-nfvpe/helm2go-operator-sdk#14]
**Describe the bug**
# github.com/redhat-nfvpe/helm2go-operator-sdk/cmd/helm2go-operator-sdk/convert
cmd/helm2go-operator-sdk/convert/chart.go:32:16: undefined: os.UserHomeDir

**To Reproduce**
go run main.go

**Expected behavior**
Should show help screen

**Comment by sjakati98** [comment]
This should be provided by golang itself? https://godoc.org/os#UserHomeDir

**Comment by sjakati98** [comment]
This may be solved by fixing the packaging issues, as described in #5

**Comment by aneeshkp** [comment]
Fixed
