### ISSUE TITLE
Deprecated version needs to be updated to current , on prompt

### ISSUE THREAD

**Issue by aneeshkp** [redhat-nfvpe/helm2go-operator-sdk#15]
**Is your feature request related to a problem? Please describe.**
helm template to  go struct fails if the helm is  using unsupported version

**Describe the solution you'd like**
Before continue, validate and prompt to user options
1. Update to next version
2. drop the one that is not supported.

**Describe alternatives you've considered**

**Additional context**

**Comment by sjakati98** [comment]
If version is deprecated, then log the deprecated version and exit program execution.

**Comment by sjakati98** [comment]
If the version, or the resource itself, is unsupported execution of the program waits on user input. Users may continue without the resource, or may stop program execution all together.
