### ISSUE TITLE
[Question] helm2go-operator-sdk vs. operator-sdk build-in helm tool

### ISSUE THREAD

**Issue by warmchang** [redhat-nfvpe/helm2go-operator-sdk#52]
Sorry, this is not a bug report, just a question:

How is helm2go-operator-sdk different from the helm tool built into the Operator SDK?
https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md

It seems that they all generate new operators through the helm chart. :thinking: 

Thanks!

**Comment by aneeshkp** [comment]
helm2go-operator-sdk converts helm templates into go struct representing k8s resources and uses go controller runtime to reconcile.  In this case, completing migrating  from helm to go. On the other hand, the helm operator provided by operator-sdk doesn't discard helm charts. So there is a tiller and helm charts dependency.

**Comment by warmchang** [comment]
@aneeshkp I understand, thank you for your reply. :+1: 

/close
