### ISSUE TITLE
Help Command Contains Typo

### ISSUE THREAD

**Issue by aneeshkp** [redhat-nfvpe/helm2go-operator-sdk#8]
**Describe the bug**
Typo "in to " should be "into"

**To Reproduce**
`go run main.go`

**Expected behavior**
`  convert     Converts an existing Helm Chart Operator into a Go Operator`

**Actual **
`  convert     Converts an existing Helm Chart Operator in to a Go Operator`

**Comment by sjakati98** [comment]
Addressed in a9f053461f8c3033300631187dc882a2248e2c23

**Comment by aneeshkp** [comment]
Fixed
