### ISSUE TITLE
sdk convert cmd  panics

### ISSUE THREAD

**Issue by aneeshkp** [redhat-nfvpe/helm2go-operator-sdk#9]
**Describe the bug**
runing  " go run main.go  convert" throws panic
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe68403]

**To Reproduce**
go run main.go convert

**Expected behavior**
Should have validation to show help screen with more details on the required command line

**Screenshots**
 🤠 Converting Existing Helm Chart  to Go Operator!           
[2019-07-02 13:24:35] Chart Is Empty! Exiting
                                    
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe68403]

goroutine 1 [running]:
github.com/redhat-nfvpe/helm2go-operator-sdk/cmd/helm2go-operator-sdk/convert.loadChart()
	/home/aputtur/gocode/src/github.com/redhat-nfvpe/helm2go-operator-sdk/cmd/helm2go-operator-sdk/convert/chart.go:23 +0x63
github.com/redhat-nfvpe/helm2go-operator-sdk/cmd/helm2go-operator-sdk/convert.convertFunc(0xc4203c6280, 0x1843348, 0x0, 0x0, 0x0, 0x0)
	/home/aputtur/gocode/src/github.com/redhat-nfvpe/helm2go-operator-sdk/cmd/helm2go-operator-sdk/convert/cmd.go:57 +0x159
github.com/redhat-nfvpe/helm2go-operator-sdk/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203c6280, 0x1843348, 0x0, 0x0, 0xc4203c6280, 0x1843348)
	/home/aputtur/gocode/src/github.com/redhat-nfvpe/helm2go-operator-sdk/vendor/github.com/spf13/cobra/command.go:826 +0x468
github.com/redhat-nfvpe/helm2go-operator-sdk/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4203c6000, 0x0, 0xc4203c6280, 0xc4203c6150)
	/home/aputtur/gocode/src/github.com/redhat-nfvpe/helm2go-operator-sdk/vendor/github.com/spf13/cobra/command.go:914 +0x306
github.com/redhat-nfvpe/helm2go-operator-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4203c6000, 0xc4200e9f70, 0x1)
	/home/aputtur/gocode/src/github.com/redhat-nfvpe/helm2go-operator-sdk/vendor/github.com/spf13/cobra/command.go:864 +0x2b
main.main()
	/home/aputtur/gocode/src/github.com/redhat-nfvpe/helm2go-operator-sdk/main.go:32 +0xcb

**Additional context**

**Comment by sjakati98** [comment]
Duplicate of #12

**Comment by aneeshkp** [comment]
Fixed
